# NpuEmbeddings -- generate the Unicode tables the C++ Whisper tokenizer needs.
# SPDX-License-Identifier: Apache-2.0
#
# WHY THIS EXISTS
# ---------------
# Whisper inherits GPT-2's byte-level BPE, whose pre-tokeniser is defined in
# terms of Unicode general categories:
#
#     's|'t|'re|'ve|'m|'ll|'d
#    | ?\p{L}+
#    | ?\p{N}+
#    | ?[^\s\p{L}\p{N}]+[\r\n]*
#    |\s+(?!\S)
#    |\s+
#
# std::regex cannot run that pattern. libstdc++ has no \p{L} at all -- it
# throws `Invalid range in '{}' in regular expression` at CONSTRUCTION time, so
# the failure is loud, which is the good kind. (A negative lookahead is no
# better: it is accepted and then does not mean what it says.) The same reason
# the WordPiece tables are generated rather than linked against ICU: a
# hand-rolled approximation of \p{L} is how a Cyrillic or CJK transcript
# silently becomes a different token sequence.
#
# So: compute the categories offline, where Python's `unicodedata` IS the
# definition HuggingFace uses, and emit static tables. The tables are then
# exactly right by construction rather than by careful reading, which is the
# same trade tools/gen_tokenizer_tables.py makes.
#
# WHAT IS FOLDED IN
# -----------------
# Three predicates, as sorted (lo, hi) range tables with a binary search:
#   is_letter  general category L*   -- the \p{L} of the pattern
#   is_number  general category N*   -- the \p{N]
#   is_space   str.isspace()         -- the \s
#
# is_space is str.isspace() and NOT a hand-written set, because that is what the
# `regex` module's Unicode \s resolves to (verified by
# tools/verify_whisper_tokenizer.py, which holds the C++ against the reference
# over a corpus that includes \x85, \xa0 and U+3000).
#
# Env: any Python 3 (no NPU, no torch, no `regex`).
# Usage:
#   python tools/gen_whisper_unicode_tables.py

import sys
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "runtime" / "include" / "tokenizers" / "whisper_unicode_tables.hpp"

MAX_CP = 0x110000


def ranges(pred):
    """Maximal [lo, hi] code point ranges where pred holds."""
    out = []
    start = None
    for cp in range(MAX_CP):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX_CP - 1))
    return out


def emit(name, rs, out):
    out.append(f"inline constexpr uint32_t {name}[][2] = {{")
    for i in range(0, len(rs), 4):
        row = ", ".join(f"{{0x{a:X}, 0x{b:X}}}" for a, b in rs[i:i + 4])
        out.append(f"    {row},")
    out.append("};")
    out.append(f"inline constexpr size_t {name}_n = {len(rs)};")
    out.append("")


def main():
    letters = ranges(lambda cp: unicodedata.category(chr(cp)).startswith("L"))
    numbers = ranges(lambda cp: unicodedata.category(chr(cp)).startswith("N"))
    spaces = ranges(lambda cp: chr(cp).isspace())

    out = [
        "//===- whisper_unicode_tables.hpp -----------------------------*- C++ -*-===//",
        "//",
        "// GENERATED by tools/gen_whisper_unicode_tables.py -- do not edit.",
        f"// Source: Python {sys.version.split()[0]}, unicodedata "
        f"{unicodedata.unidata_version}.",
        "//",
        "// The three predicates Whisper's GPT-2 pre-tokeniser pattern needs:",
        f"//   is_letter  \\p{{L}}, {len(letters)} ranges",
        f"//   is_number  \\p{{N}}, {len(numbers)} ranges",
        f"//   is_space   \\s,     {len(spaces)} ranges",
        "//",
        "// See that script for why std::regex cannot be used instead.",
        "// SPDX-License-Identifier: Apache-2.0",
        "//===----------------------------------------------------------------------===//",
        "",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace npue::whisper_unicode {",
        "",
    ]
    emit("kLetters", letters, out)
    emit("kNumbers", numbers, out)
    emit("kSpaces", spaces, out)

    out.append("""// Binary search over a sorted range table. A linear scan would be simpler and
// is measurably slower: pre-tokenisation calls these once per code point, and
// the transcript path calls it per byte of the hypothesis.
inline bool in_ranges(const uint32_t (*tab)[2], size_t n, uint32_t cp) {
  size_t lo = 0, hi = n;
  while (lo < hi) {
    const size_t mid = (lo + hi) / 2;
    if (cp < tab[mid][0]) {
      hi = mid;
    } else if (cp > tab[mid][1]) {
      lo = mid + 1;
    } else {
      return true;
    }
  }
  return false;
}

inline bool is_letter(uint32_t cp) { return in_ranges(kLetters, kLetters_n, cp); }
inline bool is_number(uint32_t cp) { return in_ranges(kNumbers, kNumbers_n, cp); }
inline bool is_space(uint32_t cp) { return in_ranges(kSpaces, kSpaces_n, cp); }

}  // namespace npue::whisper_unicode""")
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT}  ({len(letters)}+{len(numbers)}+{len(spaces)} ranges, "
          f"unicodedata {unicodedata.unidata_version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
