# NpuEmbeddings -- generate the Unicode category tables the C++ XLM-R
# tokenizer's grapheme-cluster walk needs.
# SPDX-License-Identifier: Apache-2.0
#
# WHY THIS EXISTS
# ----------------
# tools/xlmr_tokenizer_ref.py (the executable spec for the C++ port,
# tasks/0127) classifies codepoints for its UAX #29 extended-grapheme
# approximation using Python's `unicodedata.category()`: Mn/Me -> Extend,
# Mc -> SpacingMark, Cc/Cf/Zl/Zp -> Control. The C++ port
# (runtime/src/tokenizer_xlmr.cpp) must make the IDENTICAL classification
# or grapheme boundaries -- and with them the Precompiled normalizer's
# whole-cluster replacements -- drift on exactly the decomposed-diacritic
# inputs the verifier stresses. Same reasoning and same mechanism as
# tools/gen_tokenizer_tables.py -> bert_unicode_tables.hpp: compute the
# category ranges offline from the same interpreter's unicodedata
# (build-time Python is allowed, CLAUDE.md rule 5) and emit a static C++
# header, so the two implementations agree by construction.
#
# Only the three merged classes the reference actually branches on are
# emitted, not the raw categories -- the C++ consumer asks the same three
# questions the Python does, nothing more. Everything else the classifier
# needs (CR/LF/ZWJ/ZWNJ, the Prepend set, regional indicators, Hangul,
# White_Space, Extended_Pictographic) is explicit codepoint ranges in the
# reference and is transcribed directly into tokenizer_xlmr.cpp, where a
# diff against the Python shows them side by side.
#
# Env: any Python 3 (stdlib). Must be the same unicodedata generation the
# reference encoder runs under (UCD version is stamped into the header).
# Usage:
#   python tools\gen_xlmr_unicode_tables.py

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "runtime" / "include" / "xlmr_unicode_tables.hpp"

MAX_CP = 0x110000


def ranges(pred) -> list[tuple[int, int]]:
    """Compress a predicate over all codepoints into inclusive ranges."""
    out, start = [], None
    for cp in range(MAX_CP):
        if 0xD800 <= cp <= 0xDFFF:          # surrogates: never valid scalars
            continue
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX_CP - 1))
    return out


def main() -> int:
    extend = ranges(lambda cp: unicodedata.category(chr(cp)) in ("Mn", "Me"))
    spacing = ranges(lambda cp: unicodedata.category(chr(cp)) == "Mc")
    control = ranges(
        lambda cp: unicodedata.category(chr(cp)) in ("Cc", "Cf", "Zl", "Zp"))

    def emit_ranges(name, rs):
        body = ",\n    ".join(
            ", ".join(f"{{0x{a:X}, 0x{b:X}}}" for a, b in rs[i:i + 4])
            for i in range(0, len(rs), 4))
        return (f"inline constexpr CpRange {name}[] = {{\n    {body}\n}};\n"
                f"inline constexpr int {name}_n = {len(rs)};\n")

    lines = [
        "//===- xlmr_unicode_tables.hpp ------------------------------*- C++ -*-===//",
        "//",
        "// GENERATED by tools/gen_xlmr_unicode_tables.py -- DO NOT EDIT.",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// The Unicode general-category facts tokenizer_xlmr.cpp's grapheme",
        f"// classifier branches on, computed from Python {sys.version.split()[0]}'s "
        f"unicodedata (UCD {unicodedata.unidata_version})",
        "// so the C++ agrees with tools/xlmr_tokenizer_ref.py by construction.",
        "//",
        f"//   extend (Mn+Me)          {len(extend)} ranges",
        f"//   spacing_mark (Mc)       {len(spacing)} ranges",
        f"//   control (Cc+Cf+Zl+Zp)   {len(control)} ranges",
        "",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace xlmr_uni {",
        "",
        f'inline constexpr const char *kUnicodeVersion = "{unicodedata.unidata_version}";',
        "",
        "struct CpRange { uint32_t lo, hi; };",
        "",
    ]
    lines.append(emit_ranges("kExtend", extend))
    lines.append(emit_ranges("kSpacingMark", spacing))
    lines.append(emit_ranges("kControlCat", control))
    lines.append("}  // namespace xlmr_uni")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.relative_to(REPO)}  ({kb:.1f} KB)")
    print(f"  UCD {unicodedata.unidata_version}")
    print(f"  extend {len(extend)}, spacing_mark {len(spacing)}, "
          f"control {len(control)} ranges")
    return 0


if __name__ == "__main__":
    sys.exit(main())
