//===- stt_engine.cpp ------------------------------------------------*- C++ -*-===//
//
// NpuEmbeddings -- STT engine stub implementation.
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

#include "whisper/stt_engine.hpp"

namespace npue {

// STTEngine is an interface with no shared state.
// The vtable is generated by the compiler; no implementation needed here.

}  // namespace npue